# Generated by Django 6.0.1 on 2026-01-28 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_instagramcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcomment',
            name='comment_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_comments', to='social.post'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
