# Generated by Django 6.0.1 on 2026-01-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_instagramcomment_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcomment',
            name='comment_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
