# Generated by Django 6.0.1 on 2026-01-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_instagramcomment_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramcomment',
            old_name='post',
            new_name='instapostid',
        ),
    ]
