# Generated by Django 6.0.1 on 2026-01-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_rename_post_instagramcomment_instapostid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramcomment',
            old_name='instapostid',
            new_name='post',
        ),
    ]
