# Generated by Django 6.0.1 on 2026-01-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_rename_instapostid_instagramcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcomment',
            name='instagram_user_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramcomment',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.post'),
        ),
    ]
