# Generated by Django 6.0.1 on 2026-01-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_instagramcomment_instagram_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcomment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
