# Generated by Django 6.0.1 on 2026-01-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_instagramcomment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_comments', to='social.post'),
        ),
    ]
