# Generated by Django 6.0.1 on 2026-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_instagramcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
