# Generated by Django 6.0.1 on 2026-02-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_post_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], default='instagram', max_length=20),
        ),
        migrations.AddField(
            model_name='like',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], default='instagram', max_length=20),
        ),
    ]
