# Generated by Django 6.0.1 on 2026-02-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_comment_platform_like_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateprofile',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='share',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'affiliate', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('post', 'affiliate', 'platform')},
        ),
    ]
