# Generated by Django 6.0.1 on 2026-02-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_affiliateprofile_password_alter_share_platform_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'affiliate')},
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('post', 'affiliate')},
        ),
        migrations.AlterField(
            model_name='comment',
            name='platform',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], default='instagram', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='platform',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], default='instagram', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='platform',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook')], default='instagram', max_length=20, null=True),
        ),
    ]
