# Generated by Django 6.0.1 on 2026-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
