# Generated by Django 6.0.1 on 2026-02-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_post_media_type_post_media_url_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
