# Generated by Django 6.0 on 2026-02-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_comment_apify_run_id_comment_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='facebook_username',
            field=models.CharField(blank=True, help_text='Facebook name/username for verification', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Instagram username for verification', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='linkedin_username',
            field=models.CharField(blank=True, help_text='LinkedIn name for verification', max_length=150, null=True),
        ),
    ]
