# Generated by Django 6.0 on 2026-02-17 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_affiliateprofile_facebook_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('total_likes_found', models.IntegerField(default=0)),
                ('total_comments_found', models.IntegerField(default=0)),
                ('apify_run_id', models.CharField(blank=True, max_length=100, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapes', to='social.post')),
            ],
            options={
                'ordering': ['-scraped_at'],
                'unique_together': {('post', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='ScrapedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.scrapedpost')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.scrapedpost')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
