# Generated by Django 6.0.1 on 2026-02-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0021_scrapedpost_scrapedlike_scrapedcomment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "affiliate", "platform")},
        ),
        migrations.AlterUniqueTogether(
            name="share",
            unique_together={("post", "affiliate", "platform")},
        ),
    ]

