# Generated by Django 6.0 on 2026-02-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0022_alter_like_share_unique_together_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(choices=[("instagram", "Instagram"), ("facebook", "Facebook"), ("linkedin", "LinkedIn")], max_length=20)),
                ("action", models.CharField(choices=[("like", "Like"), ("share", "Share"), ("comment", "Comment")], max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("super_admin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_settings", to="social.superadmin")),
            ],
            options={
                "unique_together": {("super_admin", "platform", "action")},
            },
        ),
    ]
