# Generated by Django 6.0 on 2026-02-25

from django.db import migrations, models


def forwards_map_status_and_action(apps, schema_editor):
    WithdrawalRequest = apps.get_model("social", "WithdrawalRequest")
    for item in WithdrawalRequest.objects.all():
        old_status = (item.status or "").strip().lower()
        if old_status == "approved":
            item.status = "paid"
            item.action = "approved"
        elif old_status == "rejected":
            item.status = "pending"
            item.action = "rejected"
        else:
            item.status = "pending"
            item.action = "pending"
        item.save(update_fields=["status", "action", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0024_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="action",
            field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("paid", "Paid")], default="pending", max_length=20),
        ),
        migrations.RunPython(forwards_map_status_and_action, migrations.RunPython.noop),
    ]
