# Generated by Django 6.0 on 2026-02-25

import django.db.models.deletion
import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0025_withdrawalrequest_action_and_status_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_id", models.CharField(default=social.models.generate_payment_id, max_length=40, unique=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credits_used", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("request_date", models.DateTimeField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed")], default="paid", max_length=20)),
                ("payment_method", models.CharField(default="Manual Transfer", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("affiliate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_history", to="social.affiliateprofile")),
                ("withdrawal_request", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payment_history", to="social.withdrawalrequest")),
            ],
            options={
                "ordering": ["-paid_date", "-created_at"],
            },
        ),
    ]
