# Generated by Django 6.0 on 2026-02-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0026_paymenthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliatePaymentDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_payment_method", models.CharField(choices=[("upi", "UPI"), ("bank", "Bank Transfer"), ("upi_bank", "UPI + Bank Transfer")], default="upi", max_length=20)),
                ("upi_id", models.CharField(blank=True, default="", max_length=120)),
                ("account_holder_name", models.CharField(blank=True, default="", max_length=150)),
                ("bank_account_number", models.CharField(blank=True, default="", max_length=40)),
                ("ifsc_code", models.CharField(blank=True, default="", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("affiliate", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payment_detail", to="social.affiliateprofile")),
            ],
        ),
    ]
