# Generated by Django 6.0 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0027_affiliatepaymentdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="superadmin",
            name="minimum_withdrawal",
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
