# Generated by Django 6.0 on 2026-02-27

from decimal import Decimal
from django.db import migrations


def normalize_credits_used(apps, schema_editor):
    PaymentHistory = apps.get_model("social", "PaymentHistory")

    affiliate_ids = (
        PaymentHistory.objects.filter(status="paid")
        .values_list("affiliate_id", flat=True)
        .distinct()
    )

    for affiliate_id in affiliate_ids:
        histories = (
            PaymentHistory.objects.filter(affiliate_id=affiliate_id, status="paid")
            .order_by("paid_date", "created_at", "id")
        )

        running_total = Decimal("0.00")
        for item in histories:
            current_value = item.credits_used or Decimal("0.00")
            if current_value >= running_total:
                delta = current_value - running_total
                running_total = current_value
            else:
                # Row appears to already be a per-withdrawal delta.
                delta = current_value
                running_total = running_total + current_value

            if delta < Decimal("0.00"):
                delta = Decimal("0.00")

            item.credits_used = delta
            item.save(update_fields=["credits_used"])


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0028_superadmin_minimum_withdrawal"),
    ]

    operations = [
        migrations.RunPython(normalize_credits_used, migrations.RunPython.noop),
    ]
