# Generated by Django 6.0 on 2026-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)')], default='INR', max_length=3),
        ),
    ]
