# Generated by Django 6.0.1 on 2026-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0031_superadmin_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
