# Generated by Django 6.0 on 2026-03-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0031_superadmin_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='facebook_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='facebook_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='instagram_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='instagram_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='linkedin_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='linkedin_connected',
            field=models.BooleanField(default=False),
        ),
    ]
