# Generated by Django 6.0 on 2026-03-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0032_affiliateprofile_facebook_access_token_and_more'),
        ('social', '0032_alter_withdrawalrequest_status'),
    ]

    operations = [
    ]
