# Generated by Django 6.0 on 2026-03-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_merge_20260313_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepaymentdetail',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='affiliatepaymentdetail',
            name='preferred_payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('bank', 'Bank Transfer'), ('upi_bank', 'UPI + Bank Transfer'), ('paypal', 'PayPal')], default='upi', max_length=20),
        ),
    ]
