# Generated by Django 6.0 on 2026-03-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_affiliatepaymentdetail_paypal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='fb_page_id',
            field=models.CharField(blank=True, help_text='Facebook Page ID (e.g. 985055438020046)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='ig_account_id',
            field=models.CharField(blank=True, help_text='Instagram Business Account ID (e.g. 17841478360956917)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='li_org_id',
            field=models.CharField(blank=True, help_text='LinkedIn Organisation numeric ID (e.g. 110775771)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='n8n_webhook_url',
            field=models.URLField(blank=True, help_text="n8n webhook URL for this account's workflow", max_length=500, null=True),
        ),
    ]
